offchip_pred_type = tlp
offchip_pred_mark_merged_load = false

# TLP Configuration
tlp_flp_activated_features = 5,8,9,11,16
tlp_flp_weight_array_sizes = 1024,1024,128,1024,1024
tlp_flp_feature_hash_types = 2,2,2,2,2
tlp_flp_activation_threshold = -15
tlp_flp_max_weight = 15
tlp_flp_min_weight = -16
tlp_flp_pos_weight_delta = 1
tlp_flp_neg_weight_delta = 1
tlp_flp_pos_train_thresh = 40
tlp_flp_neg_train_thresh = -35
tlp_flp_page_buf_sets = 64
tlp_flp_page_buf_assoc = 16
tlp_flp_last_n_load_pcs = 4
tlp_flp_last_n_pcs = 4

# SLP now includes FLP's prediction as a feature (feature type 18)
tlp_slp_activated_features = 5,8,9,11,16,18
tlp_slp_weight_array_sizes = 1024,1024,128,1024,1024,1024
tlp_slp_feature_hash_types = 2,2,2,2,2,2
tlp_slp_activation_threshold = -25
tlp_slp_max_weight = 15
tlp_slp_min_weight = -16
tlp_slp_pos_weight_delta = 1
tlp_slp_neg_weight_delta = 1
tlp_slp_pos_train_thresh = 40
tlp_slp_neg_train_thresh = -25
tlp_slp_page_buf_sets = 64
tlp_slp_page_buf_assoc = 16
tlp_slp_last_n_load_pcs = 4
tlp_slp_last_n_pcs = 4

